# Generated by Django 4.2 on 2025-10-02 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youngstarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('user', 'month', 'year')},
        ),
    ]
